In [1]:
#Ax = b
#¬E|A^-1 => x = A^-1b
#A_pse = AA_pse >=< Id
#A_pse = V D_pse U.T

import numpy as np
np.set_printoptions(suppress=True)

In [2]:
A = np.array([
    [2,3],
    [5,7],
    [11,13]
])

A

array([[ 2,  3],
       [ 5,  7],
       [11, 13]])

In [3]:
U, D, V = np.linalg.svd(A)
print('U')
print(U)

print('D')
print(D)

print('V')
print(V)

U
[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
D
[19.40321383  0.71783924]
V
[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [4]:
D_pse = np.zeros((A.shape[0], A.shape[1])).T
D_pse

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
print('Valores a reemplazar en D_pse')
print(D_pse[:D.shape[0], :D.shape[0]])

Valores a reemplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [8]:
print('Valores que pondremos en D_pse')
print(np.linalg.inv(np.diag(D)))

Valores que pondremos en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [9]:
print('D_pse')
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
D_pse

D_pse


array([[0.05153785, 0.        , 0.        ],
       [0.        , 1.39306957, 0.        ]])

In [10]:
A_pse = V.T.dot(D_pse).dot(U.T)
A_pse

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [11]:
A_pse_calc = np.linalg.pinv(A)
A_pse_calc

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [12]:
print(A_pse.dot(A))

[[ 1. -0.]
 [ 0.  1.]]


In [13]:
np.set_printoptions(suppress=False)

In [14]:
print(A_pse.dot(A))

[[ 1.00000000e+00 -8.88178420e-16]
 [ 2.66453526e-15  1.00000000e+00]]


In [15]:
print(A.dot(A_pse))

[[ 0.25773196  0.43298969 -0.06185567]
 [ 0.43298969  0.74742268  0.03608247]
 [-0.06185567  0.03608247  0.99484536]]


In [16]:
A_pse_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)

In [17]:
A_pse_2

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])